### ISSUE TITLE
Release latest version 3.0.1 to npm ?

### ISSUE THREAD

**Issue by pithu** [dagrejs/graphlib#170]
Hi is there any chance to get the latest version `3.0.1` from npm. The lates i can get there is `2.1.8`

**Comment by rustedgrail** [comment]
I'll ping Chris again about the NPM permissions. I have Github permissions
but not NPM last I checked.

David Newell

**Comment by pithu** [comment]
Thanks David, 

that would be awesome. We having trouble with lodash and our rollup bundle, so a version without lodash would help us a lot.

Best Philipp

**Comment by rustedgrail** [comment]
I added a new NPM package that is the JS version without Lodash that you
can use until I can get the permissions working. Do you need Dagre or
Dagre-d3 as well?

https://www.npmjs.com/package/graphlib-2

David Newell

**Comment by pithu** [comment]
Thanks a lot. Is this the same code base as on tag 3.0.1 ? I am a bit confused why it has only a patch level version upgrade.

But honestly i would prefer to wait for a release with the npm name `graphlib`. It would save me a lot of questions from our security team. Any chance to get that ?

**Comment by rustedgrail** [comment]
This is the same code base as 3.0.1. When I took over the project, I was
trying to convert it to TypeScript. That seemed to be going well, but ran
into problems once I ran the tests in the Dagre library because of the
change to import/export from require(...) and the transpiling, so it's not
publishable for all users.

I'm talking with NPM about the permissions. It looks like I have the right
permissions, but it won't let me publish. Once that's resolved or I can at
least ask the other owners to update something specific, I should be able
to publish without issue. Hopefully I'll get this resolved in a few days.

David Newell

**Comment by rustedgrail** [comment]
I pushed a new version to ***@***.***/graphlib.
There is also a version that's not part of the Dagrejs organization that I
don't have access to. That's why I was running into issues.

David Newell

**Comment by rustedgrail** [comment]
@lutzroeder Can you add me to the NPM libraries that aren't part of the dagrejs organization?

**Comment by pithu** [comment]
Cool, thanks a lot, this version is working for us
